[package]
name = "rust-prediction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
serde = "1.0.185"
serde_json = "1.0.105"
serial_test = "2.0.0"
